# Generated by Django 4.2.9 on 2024-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='years_of_exp',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
