# Generated by Django 4.2.9 on 2024-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_user_years_of_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='years_of_exp',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
    ]
