# Generated by Django 4.2.9 on 2024-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_user_years_of_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_of_exp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
