# Generated by Django 4.2.9 on 2024-04-27 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_datetime',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='gym_location',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
