# Generated by Django 4.2.9 on 2024-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_booking_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amt',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
