# Generated by Django 4.2.9 on 2024-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_alter_booking_total_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
